[build]
  publish = "public"
  command = "npm ci && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.147.9"
  HUGO_ENV     = "production"
  NODE_VERSION = "22"
  HUGO_EXTENDED = "true"   # por si acaso

# Producción: usa TU dominio real
[context.production]
  command = "npm ci && hugo --gc --minify -b https://javiergarciaserrano.com/"

# Deploy Previews (PRs) y Branch deploys: usa la URL de Netlify del despliegue
[context.deploy-preview]
  command = "npm ci && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm ci && hugo --gc --minify -b $DEPLOY_PRIME_URL"
